<a href="https://colab.research.google.com/github/kjp07/data-python-learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Using numpy for processing arrays and matrices of number data

---

## numpy is a more efficient array processing library for Python

Python lists can contain any type of data, including objects.  numpy arrays are specialised and can only contain numbers.

You can customise the memory usage so that arrays can use less memory and items are stored contiguously.  This means that it is more efficient/faster processing large data sets.

Use numpy arrays to store and manipulate large lists of numbers (for other data types use plain Python lists or a panda series)


---
### Creating a numpy array from a Python list

To use numpy, you will need to import it.  The conventional way to import numpy is to import the whole library and use an *alias*

`import numpy as np`

Every time you want to use a function from the numpy library you use the syntax:  
`np.function_name()`  

Create a new numpy array from a Python list of numbers
   
`arr = np.array([1,2,3])`

Or a new numpy matrix from a Python 2 dimensional list of numbers

`matrix = np.array([1,2,3],[4,5,6])`

---
### Exercise 1 - create a numpy array from a given list

Write a function called `make_array(num_list`) which will:
*   accept num_list as a parameter  
*   create a new numpy array called **new_array** from `num_list`
*   print `new_array`

Test input:  
[3,6,2,5,8,6]  

Expected output:  
[3,6,2,5,8,6]  



In [1]:
import numpy as np

def make_array(num_list):
  new_array = np.array(num_list)
  print(new_array)

num_list = [3, 6, 2, 5, 8, 6]
make_array(num_list)

[3 6 2 5 8 6]


## Setting the number type in memory

numpy allows you to set the type of number in memory (e.g. int8, int32) when you create the array.  This allows memory allocation to be as small as possible.  

`new_matrix = np.array([[1, 2, 3], [4, 5, 6]], np.int8)`    

This creates a two row, three column matrix of whole numbers which are all small enough to fit in 1 byte of memory storage.

---
### Exercise 2 - create matrix of smallish numbers

Write a function which will:
*   accept a parameter **num_list** which will be a 2-dimensional list  
*   create a new numpy array called **new_matrix** from `num_list`, with data size `int16`
*   print `new_matrix` one list per line

Test input:  
[31112, 32321, 24567],[456,324,789]

Expected output:   
[31112, 32321, 24567]  
[456,324,789]  
 


In [19]:
def small_matrix(num_list):
  new_matrix = np.array(num_list, np.int16)
  for i in new_matrix:
    print(i)

num_list = [[31112, 32321, 24567],[456, 324, 789]]
small_matrix(num_list)

[31112 32321 24567]
[456 324 789]


---
### Exercise 3 - make a 3 x 3 numpy array

Write a function which  will create a 3 x 3 array, then print the array one row per line.

Test data:  
[[1,2,3],[4,5,6],[7,8,9]]

Expected output:  
[1 2 3]  
[4 5 6]  
[7 8 9]  

In [20]:
def numpy_array(num_list):
  new_matrix = np.array(num_list)
  for i in new_matrix:
    print(i)

num_list = ([1,2,3],[4,5,6],[7,8,9])
numpy_array(num_list)

[1 2 3]
[4 5 6]
[7 8 9]


---
### Exercise 4 - make a 2 x 2 x 2 numpy array

Write a function which will create a 2 x 2 x 2 array, then print the array one individual array per line.

Test data:
[[[1,2],[3,4]],[[5,6],[7,8]]]

Expected output:  
[1,2]  
[3,4]  
[5,6]  
[7,8]     

In [21]:
def numpy_array_two(num_list):
  new_matrix = np.array(num_list)
  for i, a in new_matrix:
    print(i)
    print(a)

num_list = [[[1,2],[3,4]],[[5,6],[7,8]]]
numpy_array_two(num_list,)

[1 2]
[3 4]
[5 6]
[7 8]


## Inspecting the shape of the array/matrix

numpy provides the `np.shape` property for reporting the shape of a numpy array.  np.shape will give the number of layers, rows, columns (and more if necessary) present in the array.  Arrays can be multi-dimensional but we will only arrays of maximum 3 dimensions to keep it simple.  

Example:  
```
matrix = np.array([[[1,1],[2,2],[3,3]],[[4,4],[5,5],[6,6]]])
print(matrix.shape)
```

Expected output:  
(2, 3, 2)

This matrix has 2 layers of 3 rows of 2 columns

---
### Exercise 5 - print the shape

Write a function which will:  
*  create a numpy array using the test data below
*  print the shape of the array

Test 1 data:  
[3,7,56]

Expected output:
(3,)

Test 2 data:  
[[7,6,5,8,4,9],[3,7,5,8,6,9]]

Expected output:  
(2,6)

In [5]:
def print_array_shape():
  array_one = np.array([3,7,56])
  array_two = np.array([[7, 6, 5, 8, 4, 9],[3, 7, 5 , 8, 6, 9]])
  print(array_one.shape)
  print(array_two.shape)

print_array_shape()

(3,)
(2, 6)


---
### Exercise 6 - using slicing to print parts of arrays

Write a function which will:  
*  create an array from the Python list [1,2,3,4,5]
*  print the first 3 items in the array
*  print the last item in the array

In [6]:
def array_slices():
  num_list = [1, 2, 3, 4, 5]
  array = np.array(num_list)
  print(array[0:3])
  print(array[-1])

array_slices()

[1 2 3]
5


---
### Exercise 7 - using slicing to print parts of array rows and columns

Write a function which will:  
*  create an array from the Python 2 dimsensional list [[1,2,3,4],[5,6,7,8],[9,1,2,3]]
*  print the first item in the second row   
*  print the first 2 rows only
*  print the last 2 items in the last 2 rows

Expected output:  
5  
[[1,2,3,4],[5,6,7,8]]  
[[7,8],[2,3]]

In [27]:
import numpy as np

def slice_rows_cols():
  num_array = np.array([[1,2,3,4],[5,6,7,8],[9,1,2,3]])
  
  # First part specifies the row index, second part specifies the column
  print(num_array[1,0])
  print(num_array[0:2])
  print(*num_array[1:3, -2:])

slice_rows_cols()

5
[[1 2 3 4]
 [5 6 7 8]]
[7 8] [2 3]


---
## Broadcasting an operation across an array

Because a numpy array is created from a related set of data, it is useful to be able to operate on every item in the array in the same way.  For instance, the array might hold a set of scores out of 30 and you might want to convert all scores into percentages.

We can do this in a number of ways:  
1.  Create a new array to store the result after the operation in the new array
```
scores = np.array([29,25,15,22,30])
percentages = scores / 30 * 100
print(percentages)
```
Expected output:  [ 96.66666667  83.33333333  50.  73.33333333 100. ]  

2.  Store the result in the original array
```
scores = np.array([29,25,15,22,30])
scores = scores / 30 * 100
print(scores)
```
Expected output:  [ 96.66666667  83.33333333  50.  73.33333333 100. ]

Give it a try:





In [8]:
scores = np.array([26,25,15,22,30])
percentages = scores / 30 * 100
print(percentages)

[ 86.66666667  83.33333333  50.          73.33333333 100.        ]


---
### Exercise 8 - increase whole array by 20

Write a function which will:
*  create a numpy array of 12 numbers
*  create a new array adding 20 to each of the items in the first array  
*  print the new array

Test input:  
[1,2,3,4,5,6,7,8,1,2,3,4]  

Expected output:  
[21,22,23,24,25,26,27,28,21,22,23,24]

In [9]:
def increase_array():
  twelve_nums = np.array([1,2,3,4,5,6,7,8,1,2,3,4])
  increased_nums = twelve_nums + 20
  print(increased_nums)

increase_array()

[21 22 23 24 25 26 27 28 21 22 23 24]


---
## Using functions to create arrays of 1s, 0s or a range of numbers

You can use np.arange(range) to create an array with a range of numbers.  Like range in Python, either give 1 number to get all numbers from 0 to the number before it, or give 2 numbers to get the numbers from the first to one before the last.  You can specify the start number, the stop number and a step size (e.g. (1,9,2) will generate [1 3 5 7]:
```
array1 = np.arange(10)
```
will give array1 = [0,1,2,3,4,5,6,7,8,9]

```
array2 = np.arange(2,9)
```
will give array2 = [2,3,4,5,6,7,8]

```
array3 = np.arange(2,9,3)
```
will give array3 = [2,5,8]  

---

To create a new array of 10 zeros:
```
array4 = np.zeros(10)
```
will give array4 = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

To create a new array of 10 zeros as integers:
```
array5 = np.zeros(10, dtype='int32')
```
will give array5 = [0 0 0 0 0 0 0 0 0 0]

To create a new array of 8 ones:  
```
array6 = np.ones(8, dtype='int16')
```
will give array6 = [1 1 1 1 1 1 1 1]

---
### Exercise 9 - create a numpy array of the numbers 1 to 8  

Write a function which will:  
*  create a numpy array with the numbers 1 to 8 using np.arange()  
*  create a second numpy array with 12 zeros
*  create a third numpy array with 4 ones
*  create a fourth numpy array with the the multiples of 10 from 10 to 100 (use arange with start, stop and step)

Expected output:  
[1 2 3 4 5 6 7 8]  
[0 0 0 0 0 0 0 0 0 0 0 0]  
[1 1 1 1]  
[ 10  20  30  40  50  60  70  80  90 100]


 

In [10]:
def create_array():
  array_one = np.arange(9)
  array_two = np.zeros(12, dtype="int32")
  array_three = np.ones(4, dtype="int32")
  array_four = np.arange(10, 101, 10)
  print(array_one)
  print(array_two)
  print(array_three)
  print(array_four)

create_array()

[0 1 2 3 4 5 6 7 8]
[0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1]
[ 10  20  30  40  50  60  70  80  90 100]


---
### Exercise 10 - create a numpy mask matrix

**Challenging**

Write a function which will create and print a numpy array as follows:

*  create **array1** with shape=(8,8) containing all zeros of dtype int16
*  change the value of the middle two items of the middle two rows of `array1`, each to 1 (use list indexing for this)
*  print `array1`
*  change the value of the corner items to 1
*  print `array1`

Expected output:  
[[0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 1 1 0 0 0]  
 [0 0 0 1 1 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]]    

 [[1 0 0 0 0 0 0 1]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 1 1 0 0 0]  
 [0 0 0 1 1 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [1 0 0 0 0 0 0 1]]  



In [11]:
def numpy_mask():
  array1 = np.zeros((8,8), dtype="int32")
  array1[3:5, 3:5] = 1
  print(array1)
  array1[0, 0] = 1
  array1[0, -1] = 1
  array1[-1, 0] = 1
  array1[-1, -1] = 1 
  print(array1)

numpy_mask()

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0]
 [0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0]
 [0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1]]
